import type {
  Opportunity,
  UserProfile,
  Badge,
  Application,
  Achievement,
  LeaderboardEntry,
} from './types';

export const mockUser: UserProfile = {
  id: '1',
  name: 'Alex Rivera',
  email: 'alex@university.edu',
  educationLevel: 'Undergraduate',
  university: 'MIT',
  country: 'United States',
  skills: ['React', 'Python', 'Machine Learning', 'UI/UX Design', 'Solidity'],
  interests: ['AI/ML', 'Web3', 'Climate Tech', 'EdTech'],
  careerGoals: ['AI Engineer', 'Startup Founder'],
  preferredIndustries: ['Technology', 'Finance', 'Healthcare'],
  preferredCountries: ['United States', 'United Kingdom', 'Singapore', 'Germany'],
  bio: 'CS student passionate about AI and Web3. Building the future one project at a time.',
  xp: 2450,
  level: 12,
  streak: 7,
  badges: [],
  onboardingComplete: true,
};

export const mockBadges: Badge[] = [
  { id: '1', name: 'Early Adopter', description: 'Joined OpportunityOS in the first week', icon: 'Rocket', rarity: 'legendary', earnedAt: '2024-01-15' },
  { id: '2', name: 'Profile Pro', description: 'Completed 100% of your profile', icon: 'User', rarity: 'common', earnedAt: '2024-01-16' },
  { id: '3', name: 'First Application', description: 'Submitted your first application', icon: 'Send', rarity: 'common', earnedAt: '2024-01-20' },
  { id: '4', name: 'Hackathon Hero', description: 'Applied to 5 hackathons', icon: 'Code', rarity: 'rare', earnedAt: '2024-02-01' },
  { id: '5', name: 'Streak Master', description: 'Maintained a 7-day streak', icon: 'Flame', rarity: 'rare', earnedAt: '2024-02-10' },
  { id: '6', name: 'Scholar', description: 'Applied to 10 scholarships', icon: 'GraduationCap', rarity: 'epic', earnedAt: '2024-02-20' },
  { id: '7', name: 'Global Explorer', description: 'Explored opportunities in 5+ countries', icon: 'Globe', rarity: 'epic' },
  { id: '8', name: 'AI Whisperer', description: 'Used AI assistant 50 times', icon: 'Bot', rarity: 'legendary' },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Google Summer of Code 2025',
    organization: 'Google',
    category: 'internship',
    deadline: '2025-04-15',
    eligibility: 'University students 18+',
    location: 'Remote',
    description: 'Contribute to open source projects with Google mentors. Stipend provided.',
    tags: ['Open Source', 'Coding', 'Remote', 'Paid'],
    amount: '$3,000 - $6,600',
    url: '#',
    featured: true,
  },
  {
    id: '2',
    title: 'Chevening Scholarship',
    organization: 'UK Government',
    category: 'scholarship',
    deadline: '2024-11-05',
    eligibility: 'Undergraduate degree, 2 years work experience',
    location: 'United Kingdom',
    description: 'Fully-funded master\'s degree in any subject at any UK university.',
    tags: ['Fully Funded', 'Masters', 'Global', 'Prestigious'],
    amount: 'Full Tuition + Stipend',
    url: '#',
    featured: true,
  },
  {
    id: '3',
    title: 'Solana Hyperdrive Hackathon',
    organization: 'Solana Foundation',
    category: 'hackathon',
    deadline: '2024-10-15',
    eligibility: 'Open to everyone',
    location: 'Online',
    description: 'Global online hackathon with $1M in prizes. Build the future of Web3.',
    tags: ['Web3', 'Crypto', 'Prize Money', 'Global'],
    amount: 'Up to $50,000',
    url: '#',
    featured: true,
  },
  {
    id: '4',
    title: 'Microsoft Explore Program',
    organization: 'Microsoft',
    category: 'internship',
    deadline: '2024-12-01',
    eligibility: 'First and second-year college students',
    location: 'Redmond, WA',
    description: '12-week summer internship program designed specifically for college freshmen and sophomores.',
    tags: ['Big Tech', 'Summer 2025', 'Paid', 'Mentorship'],
    amount: '$7,500/month',
    url: '#',
    featured: false,
  },
  {
    id: '5',
    title: 'Y Combinator Summer 2025',
    organization: 'Y Combinator',
    category: 'incubator',
    deadline: '2025-02-15',
    eligibility: 'Founders with an idea or early-stage startup',
    location: 'San Francisco, CA (Hybrid)',
    description: 'The premier startup accelerator program. $500k investment for 7% equity.',
    tags: ['Startups', 'Funding', 'Network', 'Silicon Valley'],
    amount: '$500,000',
    url: '#',
    featured: true,
  },
  {
    id: '6',
    title: 'ETHGlobal Bangkok',
    organization: 'ETHGlobal',
    category: 'hackathon',
    deadline: '2025-05-20',
    eligibility: 'Open to all developers',
    location: 'Bangkok, Thailand',
    description: 'Build and ship the next generation of Web3 applications. $500k+ in total prizes across tracks.',
    tags: ['Ethereum', 'Web3', 'DeFi', 'NFT'],
    amount: '$100,000+',
    url: '#',
    featured: true,
  },
  {
    id: '7',
    title: 'Rhodes Scholarship 2026',
    organization: 'Rhodes Trust',
    category: 'scholarship',
    deadline: '2025-09-30',
    eligibility: 'Final year undergrad, age 19-25',
    location: 'Oxford, UK',
    description: 'The oldest and most celebrated international scholarship programme. Full Oxford funding plus stipend.',
    tags: ['Prestigious', 'Fully Funded', 'Oxford', 'Leadership'],
    amount: 'Full Tuition + £18,180/yr',
    url: '#',
    featured: false,
  },
  {
    id: '8',
    title: 'OpenAI Startup Fund',
    organization: 'OpenAI',
    category: 'grant',
    deadline: '2025-06-01',
    eligibility: 'AI-focused startups pre-series A',
    location: 'Remote',
    description: "OpenAI's $100M fund for companies using AI to tackle the world's biggest problems.",
    tags: ['AI', 'Grant', 'Startup', 'Remote'],
    amount: 'Up to $1,000,000',
    url: '#',
    featured: false,
  },
  {
    id: '9',
    title: 'Solana Foundation Developer Grant',
    organization: 'Solana Foundation',
    category: 'grant',
    deadline: '2025-07-15',
    eligibility: 'Developers building on Solana',
    location: 'Remote',
    description: 'Get funded to build open-source tooling, dApps, and infrastructure on Solana.',
    tags: ['Solana', 'Web3', 'Open Source', 'Grant'],
    amount: '$5,000 - $50,000',
    url: '#',
    featured: true,
  },
  {
    id: '10',
    title: 'Meta Software Engineering Internship',
    organization: 'Meta',
    category: 'internship',
    deadline: '2025-03-01',
    eligibility: '3rd/4th year CS students',
    location: 'Menlo Park, CA',
    description: 'Join Meta\'s engineering teams working on Instagram, WhatsApp, VR/AR, and AI infrastructure.',
    tags: ['Big Tech', 'Paid', 'AI', 'Summer 2025'],
    amount: '$8,500/month',
    featured: false,
  },
  {
    id: '11',
    title: 'Chevening Scholarship 2026',
    organization: 'UK Government',
    category: 'scholarship',
    deadline: '2025-11-05',
    eligibility: 'Mid-career professionals, global',
    location: 'United Kingdom',
    description: 'Fully-funded master\'s degree scholarship to study at any UK university for emerging global leaders.',
    tags: ['Fully Funded', 'Masters', 'Leadership', 'UK'],
    amount: 'Full Tuition + Stipend',
    url: '#',
    featured: true,
  },
  {
    id: '12',
    title: 'Stripe Open Source Retreat',
    organization: 'Stripe',
    category: 'grant',
    deadline: '2025-04-15',
    eligibility: 'Open source contributors',
    location: 'Remote',
    description: 'A 3-month grant to work full-time on the open-source project of your choice with mentorship from Stripe engineers.',
    tags: ['Open Source', 'Remote', 'Grant'],
    amount: '$25,000',
    url: '#',
    featured: false,
  },
  {
    id: '13',
    title: 'Apple AI Research Fellowship',
    organization: 'Apple',
    category: 'fellowship',
    deadline: '2025-08-01',
    eligibility: 'PhD Students in AI/ML',
    location: 'Cupertino, CA',
    description: 'Recognizes outstanding graduate students with innovative research in machine learning and AI.',
    tags: ['AI/ML', 'PhD', 'Research'],
    amount: '$50,000 + Intern Offer',
    url: '#',
    featured: true,
  },
  {
    id: '14',
    title: 'Global Climate Tech Hackathon',
    organization: 'Techstars',
    category: 'hackathon',
    deadline: '2025-06-10',
    eligibility: 'Developers, designers, scientists',
    location: 'Remote',
    description: 'Build software solutions to accelerate the transition to a sustainable, low-carbon future.',
    tags: ['Climate Tech', 'Sustainability', 'Global'],
    amount: '$50,000 Prize Pool',
    url: '#',
    featured: false,
  },
  {
    id: '15',
    title: 'Binance Labs Incubation Season 7',
    organization: 'Binance Labs',
    category: 'incubator',
    deadline: '2025-02-28',
    eligibility: 'Early-stage Web3 startups',
    location: 'Dubai / Remote',
    description: 'An intensive 8-week program designed to empower innovative projects building the future of Web3.',
    tags: ['Web3', 'Crypto', 'Incubator', 'Dubai'],
    amount: 'Seed Funding',
    url: '#',
    featured: true,
  },
  {
    id: '16',
    title: 'Google DeepMind Residency',
    organization: 'Google DeepMind',
    category: 'job',
    deadline: '2025-05-30',
    eligibility: 'Recent grads or career transitioners',
    location: 'London, UK',
    description: 'A 12-month paid program to jumpstart a career in AI and machine learning research and engineering.',
    tags: ['AI', 'Research', 'London'],
    amount: 'Competitive Salary',
    url: '#',
    featured: true,
  },
  {
    id: '17',
    title: 'NASA Space Apps Challenge',
    organization: 'NASA',
    category: 'competition',
    deadline: '2025-10-01',
    eligibility: 'Open to everyone',
    location: 'Global (Local & Virtual)',
    description: 'The largest annual global hackathon using open data from NASA and space agency partners to solve real-world problems.',
    tags: ['Space', 'Data', 'Global', 'Hackathon'],
    amount: 'Global Awards',
    url: '#',
    featured: false,
  },
  {
    id: '18',
    title: 'Fulbright Foreign Student Program',
    organization: 'US Department of State',
    category: 'scholarship',
    deadline: '2025-10-15',
    eligibility: 'International graduate students',
    location: 'United States',
    description: 'Enables graduate students, young professionals and artists from abroad to study and conduct research in the US.',
    tags: ['International', 'Research', 'USA', 'Fully Funded'],
    amount: 'Full Funding',
    url: '#',
    featured: true,
  },
  {
    id: '19',
    title: 'Vercel Frontend Engineering Intern',
    organization: 'Vercel',
    category: 'internship',
    deadline: '2025-03-15',
    eligibility: 'Undergraduate or Master\'s students',
    location: 'Remote',
    description: 'Help build the next iteration of the Web. Work closely with the Next.js core team on cutting edge web infrastructure.',
    tags: ['Frontend', 'Next.js', 'Remote', 'Summer 2025'],
    amount: '$7,000/month',
    url: '#',
    featured: false,
  },
  {
    id: '20',
    title: 'Vitalik Buterin Fellowship',
    organization: 'Ethereum Foundation',
    category: 'fellowship',
    deadline: '2025-07-20',
    eligibility: 'Cryptography/blockchain researchers',
    location: 'Remote',
    description: 'Supports high-impact research in cryptography, distributed systems, and economics related to Ethereum.',
    tags: ['Ethereum', 'Cryptography', 'Research'],
    amount: '$100,000',
    url: '#',
    featured: true,
  }
];

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    opportunityId: '1',
    status: 'under_review',
    appliedAt: '2024-03-01T10:00:00Z',
    lastUpdated: '2024-03-10T14:30:00Z',
  },
  {
    id: 'app-2',
    opportunityId: '3',
    status: 'accepted',
    appliedAt: '2024-02-15T09:00:00Z',
    lastUpdated: '2024-03-05T11:20:00Z',
  }
];

export const mockAchievements: Achievement[] = [
  { id: '1', title: 'Profile Setup', description: 'Completed onboarding', date: '2024-01-10', xp: 50 },
  { id: '2', title: 'First Application', description: 'Applied to GSoC', date: '2024-03-01', xp: 100 },
  { id: '3', title: 'Hackathon Winner', description: 'Top 10 in Solana Hyperdrive', date: '2024-03-05', xp: 500 },
];

export const categoryConfig: Record<string, { label: string; color: string; icon: string }> = {
  scholarship: { label: 'Scholarship', color: '#7c3aed', icon: 'GraduationCap' },
  job: { label: 'Job', color: '#22c55e', icon: 'Briefcase' },
  internship: { label: 'Internship', color: '#0ea5e9', icon: 'Building2' },
  hackathon: { label: 'Hackathon', color: '#f59e0b', icon: 'Code' },
  grant: { label: 'Grant', color: '#f97316', icon: 'Coins' },
  fellowship: { label: 'Fellowship', color: '#a855f7', icon: 'Award' },
  competition: { label: 'Competition', color: '#ef4444', icon: 'Trophy' },
  incubator: { label: 'Incubator', color: '#06b6d4', icon: 'Rocket' },
};

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, id: 'u1', name: 'Sarah Chen', avatar: 'SC', country: 'Singapore', xp: 15420, badges: 24, level: 32 },
  { rank: 2, id: 'u2', name: 'David Kumar', avatar: 'DK', country: 'India', xp: 14850, badges: 21, level: 31 },
  { rank: 3, id: 'u3', name: 'Alex Rivera', avatar: 'AR', country: 'United States', xp: 14200, badges: 19, level: 30 },
  { rank: 4, id: 'u4', name: 'Elena Rossi', avatar: 'ER', country: 'Italy', xp: 13900, badges: 18, level: 29 },
  { rank: 5, id: 'u5', name: 'James Wilson', avatar: 'JW', country: 'UK', xp: 12500, badges: 15, level: 28 },
  { rank: 6, id: 'u6', name: 'Yuki Tanaka', avatar: 'YT', country: 'Japan', xp: 11800, badges: 14, level: 27 },
  { rank: 7, id: 'u7', name: 'Maria Garcia', avatar: 'MG', country: 'Spain', xp: 10950, badges: 12, level: 26 },
  { rank: 8, id: 'u8', name: 'Ahmed Hassan', avatar: 'AH', country: 'Egypt', xp: 9800, badges: 10, level: 24 },
];

export const getLevelProgress = (xp: number, level: number) => {
  // Simple calculation: 1000 XP per level
  const xpInCurrentLevel = xp % 1000;
  return (xpInCurrentLevel / 1000) * 100;
};
